"""Initial migration with all models and indexes

Revision ID: 5ef50b68bb41
Revises: 
Create Date: 2026-07-06 11:16:35.068777+08:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ef50b68bb41'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # SQLite 需要批量模式来添加约束
    with op.batch_alter_table('announcements', recreate='always') as batch_op:
        batch_op.add_column(sa.Column('is_favorited', sa.Boolean(), nullable=True, comment='是否收藏'))
        batch_op.create_unique_constraint('uq_announcements_source_url', ['source_url'])
        batch_op.create_index('ix_announcements_announce_date', ['announce_date'], unique=False)
        batch_op.create_index('ix_announcements_category_date', ['project_category', 'announce_date'], unique=False)
        batch_op.create_index('ix_announcements_city', ['city'], unique=False)
        batch_op.create_index('ix_announcements_city_date', ['city', 'announce_date'], unique=False)
        batch_op.create_index('ix_announcements_is_favorited', ['is_favorited'], unique=False)
        batch_op.create_index('ix_announcements_project_category', ['project_category'], unique=False)
        batch_op.create_index('ix_announcements_purchaser_id', ['purchaser_id'], unique=False)

    with op.batch_alter_table('client_relations', recreate='always') as batch_op:
        batch_op.create_index('ix_client_relations_next_followup', ['next_followup_date'], unique=False)
        batch_op.create_index('ix_client_relations_purchaser_id', ['purchaser_id'], unique=False)
        batch_op.create_index('ix_client_relations_rating', ['rating'], unique=False)

    with op.batch_alter_table('historical_awards', recreate='always') as batch_op:
        batch_op.create_index('ix_historical_awards_bid_open_date', ['bid_open_date'], unique=False)
        batch_op.create_index('ix_historical_awards_project_category', ['project_category'], unique=False)
        batch_op.create_index('ix_historical_awards_purchaser_id', ['purchaser_id'], unique=False)
        batch_op.create_index('ix_historical_awards_winner_name', ['winner_name'], unique=False)

    with op.batch_alter_table('project_relation_alerts', recreate='always') as batch_op:
        batch_op.create_index('ix_project_relation_alerts_announcement_id', ['announcement_id'], unique=False)
        batch_op.create_index('ix_project_relation_alerts_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_project_relation_alerts_is_read', ['is_read'], unique=False)
        batch_op.create_index('ix_project_relation_alerts_relation_id', ['relation_id'], unique=False)

    with op.batch_alter_table('purchasers', recreate='always') as batch_op:
        batch_op.create_index('ix_purchasers_level', ['level'], unique=False)
        batch_op.create_index('ix_purchasers_name', ['name'], unique=False)
        batch_op.create_index('ix_purchasers_region', ['region'], unique=False)

    with op.batch_alter_table('user_preferences', recreate='always') as batch_op:
        batch_op.add_column(sa.Column('llm_enabled', sa.String(length=10), nullable=True, comment='LLM是否启用'))
        batch_op.add_column(sa.Column('llm_api_key', sa.Text(), nullable=True, comment='LLM API Key'))
        batch_op.add_column(sa.Column('llm_model', sa.String(length=100), nullable=True, comment='LLM模型'))
        batch_op.add_column(sa.Column('llm_base_url', sa.Text(), nullable=True, comment='LLM API地址'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'llm_base_url')
    op.drop_column('user_preferences', 'llm_model')
    op.drop_column('user_preferences', 'llm_api_key')
    op.drop_column('user_preferences', 'llm_enabled')
    op.drop_index('ix_purchasers_region', table_name='purchasers')
    op.drop_index('ix_purchasers_name', table_name='purchasers')
    op.drop_index('ix_purchasers_level', table_name='purchasers')
    op.drop_index('ix_project_relation_alerts_relation_id', table_name='project_relation_alerts')
    op.drop_index('ix_project_relation_alerts_is_read', table_name='project_relation_alerts')
    op.drop_index('ix_project_relation_alerts_created_at', table_name='project_relation_alerts')
    op.drop_index('ix_project_relation_alerts_announcement_id', table_name='project_relation_alerts')
    op.drop_index('ix_historical_awards_winner_name', table_name='historical_awards')
    op.drop_index('ix_historical_awards_purchaser_id', table_name='historical_awards')
    op.drop_index('ix_historical_awards_project_category', table_name='historical_awards')
    op.drop_index('ix_historical_awards_bid_open_date', table_name='historical_awards')
    op.drop_index('ix_client_relations_rating', table_name='client_relations')
    op.drop_index('ix_client_relations_purchaser_id', table_name='client_relations')
    op.drop_index('ix_client_relations_next_followup', table_name='client_relations')
    op.drop_constraint('uq_announcements_source_url', 'announcements', type_='unique')
    op.drop_index('ix_announcements_purchaser_id', table_name='announcements')
    op.drop_index('ix_announcements_project_category', table_name='announcements')
    op.drop_index('ix_announcements_is_favorited', table_name='announcements')
    op.drop_index('ix_announcements_city_date', table_name='announcements')
    op.drop_index('ix_announcements_city', table_name='announcements')
    op.drop_index('ix_announcements_category_date', table_name='announcements')
    op.drop_index('ix_announcements_announce_date', table_name='announcements')
    op.drop_column('announcements', 'is_favorited')
    # ### end Alembic commands ###
